# 2. Creating PVC
# pvc-dv.yaml
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: my-disk-claim-1
spec:
  resources:
    requests:
      storage: 5Gi
  accessModes:
    - ReadWriteOnce
  storageClassName: fast
